# Generated by Django 4.1.7 on 2023-03-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
